# Setup
title:        DroidRise
tagline:      伟大复兴！
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       DroidRise
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
highlighter: rouge  
markdown: kramdown
theme: jekyll-theme-cayman
